---

- name: Gather service facts
  ansible.builtin.service_facts:

- name: Install Ollama
  ansible.builtin.shell: curl -fsSL https://ollama.com/install.sh | sh
  when: "'ollama.service' not in ansible_facts.services"

