---

- name: Run the Ollama/Open-WebUI container
  community.docker.docker_container:
    name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    state: started
    restart_policy: always
    network_mode: host
    volumes:
      - "open-webui:/app/backend/data"
    env:
      OLLAMA_BASE_URL: "http://{{ llm_address }}:11434"
      OPENAI_API_KEY: "{{ openai_api }}"
    detach: yes
  ignore_errors: yes

- name: Run redis container
  community.docker.docker_container:
    name: redis
    image: redis:7.2
    state: started
    restart_policy: always
    network_mode: host
    detach: yes
