---

- name: Update apt and install prerequisites
  apt:
    update_cache: yes
    name: ca-certificates,curl
    state: present

- name: Create Docker's apt keyring directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker's official GPG key
  ansible.builtin.shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    chmod a+r /etc/apt/keyrings/docker.asc

- name: Add Docker repository to Apt sources for Pop!_OS/Ubuntu
  ansible.builtin.shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$UBUNTU_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  args:
    executable: /bin/bash
  notify: Update apt cache

- name: Install Docker packages
  apt:
    name: docker-ce,docker-ce-cli,containerd.io,docker-buildx-plugin,docker-compose-plugin
    state: present
    update_cache: yes

- name: Run Docker hello-world
  ansible.builtin.shell: docker run hello-world
