---

- name: Add repos
  apt_repository:
    repo: 'ppa:jonaski/strawberry'

- name: Get the non root remote user                                                                                           
  set_fact:
    remote_user: "{{ ansible_env.SUDO_USER or ansible_user_id }}"

- name: Include packages
  import_tasks: "packages.yml"

- name: Vim config
  import_tasks: "vim.yml"

- name: Create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
  loop:
    - "/home/{{ remote_user }}/.config/i3blocks"
    - "/home/{{ remote_user }}/.config/i3"

- name: Deploy i3 config
  copy:
    src: files/i3.conf
    dest: "/home/{{ remote_user }}/.config/i3/config" 
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
    mode: 0644

- name: Deploy i3blocks config
  copy:
    src: files/i3blocks.conf
    dest: "/home/{{ remote_user }}/.config/i3blocks/i3blocks.conf"
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
    mode: 0644


- name: Deploy picom config
  copy:
    src: files/picom.conf
    dest: "/home/{{ remote_user }}/.config/picom/picom.conf"
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
    mode: 0644

- name: env variable for kitty janky ssh behaviour
  lineinfile:
    path: "/home/{{ remote_user }}/.bashrc"
    line: 'export TERM="xterm-256color"'
    create: no
    state: present
    insertafter: EOF

- name: Clone kitty themes repository
  git:
    repo: 'https://github.com/dexpota/kitty-themes.git'
    dest: "/home/{{ remote_user }}/.config/kitty/kitty-themes"
    depth: 1
    clone: yes
    update: no

- name: Apply kitty theme
  file:
    src: "/home/{{ remote_user }}/.config/kitty/kitty-themes/themes/Misterioso.conf"
    dest: "/home/{{ remote_user }}/.config/kitty/theme.conf"
    state: link
    force: yes
