---

- name: Run "apt update"
  apt:
    update_cache: yes

- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest

- name: Install baseline packages
  apt:
    pkg:
      - vim
      - htop
      - i3
      - i3blocks
      - compton
      - xautolock
      - compton
      - suckless-tools
      - lxappearance
      - gparted
      - synaptic
      - curl
      - whois
      - net-tools
      - pcmanfm
      - nextcloud-desktop
      - sirikali
      - encfs
      - git
      - hexchat

- name: Remove packages
  apt:
    pkg:
      - rhythmbox
      - gnome-games
      - aisleriot
      - four-in-a-row
      - gnome-chess
      - gnome-sudoku
      - gnome-taquin
      - gnome-tetravex
      - hoichess
      - lightsoff
      - quadrapassel
      - swell-foop
    state: absent

- name: Clean up downloaded packages 
  ansible.builtin.apt:
    autoclean: yes

- name: Remove old dependencies
  ansible.builtin.apt:
    autoremove: yes

- name: Get the non root remote user
  set_fact:
    remote_user: "{{ ansible_env.SUDO_USER or ansible_user_id }}"

- name: Create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
  loop:
    - "/home/{{ remote_user }}/.config/i3blocks"
    - "/home/{{ remote_user }}/.config/i3"

- name: Deploy i3 config
  copy:
    src: files/i3.conf
    dest: "/home/{{ remote_user }}/.config/i3/config" 
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
    mode: 0644

- name: Deploy i3blocks config
  copy:
    src: files/i3blocks.conf
    dest: "/home/{{ remote_user }}/.config/i3blocks/i3blocks.conf"
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
    mode: 0644

- name: Deploy compton config
  copy:
    src: files/compton.conf
    dest: "/home/{{ remote_user }}/.config/compton.conf"
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
    mode: 0644

- name: Deploy vim config
  copy:
    src: files/vim.conf
    dest: "/home/{{ remote_user }}/.vimrc"
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
    mode: 0644

- name: Clone Vundle for vim plugins
  ansible.builtin.git:
    repo: 'https://github.com/gmarik/Vundle.vim.git'
    dest: "/home/{{ remote_user }}/.vim/bundle/Vundle.vim"
    update: yes

- name: Recursively change ownership
  file:
    path: "/home/{{ remote_user }}/.vim/"
    state: directory
    recurse: yes
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"

- name: Install vundle plugins
  shell: 
    cmd: |
      vim -E -s -c "source ~/.vimrc" -c PluginInstall -c qa
  become: true
  become_user: "{{ remote_user }}"
  ignore_errors: true

- name: Include synchting
  ansible.builtin.include_tasks: syncthing.yml
