---

- name: Run "apt update"
  apt:
    update_cache: yes

- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest

- name: Install baseline packages
  apt:
    pkg:
      - vim
      - i3
      - i3blocks
      - xautolock
      - compton
      - suckless-tools
      - lxappearance
      - gparted
      - synaptic
      - curl
      - whois
      - net-tools
      - pcmanfm
      - git
      - hexchat
