---
- name: Ensure /etc/apt/keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Syncthing GPG key
  ansible.builtin.get_url:
    url: https://syncthing.net/release-key.gpg
    dest: /etc/apt/keyrings/syncthing-archive-keyring.gpg
    mode: '0644'

- name: Add Syncthing repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/syncthing.list
    line: "deb [signed-by=/etc/apt/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing stable"
    create: yes

- name: Install Syncthing
  ansible.builtin.apt:
    name: syncthing
    state: present
    update-cache: false

